//food and beverage


//electronics
 GET https://mocki.io/v1/0a8e2cbc-e596-4fe5-b756-29cc94cfe284

//beauty
GET https://mocki.io/v1/4def05dd-55bf-4304-807f-bf4a0d991073

//foodfront
GET https://mocki.io/v1/1df01d70-b50d-42c3-820b-171e61bceb3e

# foodcategory

GET https://mocki.io/v1/45a0c6a5-b0e9-470b-b840-f8d5e1cdc21f
